# Generated by Django 3.2.7 on 2021-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admins',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=222),
        ),
    ]
